### ISSUE TITLE
No _fas.ffindex files in Uniclust database

### ISSUE THREAD

**Issue by pavlohrab** [Alexamk/RREFinder#10]
Hi, 

I was trying to run the the exploratory mode with Uniclust database, as described in 3rd step of "Use RREFinder to detect RREs with the uniclust30 database (Advanced)" section:
```
 resubmit_database=path/to/uniclust30
 expand_database=path/to/uniclust30
```
But eventually the following error arises:
```
Traceback (most recent call last):
  File "RRE.py", line 1400, in <module>
    check_databases(settings)
  File "RRE.py", line 1374, in check_databases
    raise ValueError(f'File {file} for category {category} not found. Please make sure all required databases are downloaded and their paths indicated in the config file.')
ValueError: File UniRef30_2021_03_fas.ffindex for category exploratory_hhpred_resubmit_database not found. Please make sure all required databases are downloaded and their paths indicated in the config file.
```

And there are no _fas.ffindex in Uniclust30 database.

Best,
Pavlo

**Comment by Alexamk** [comment]
Hi, 
I assumed that _fas files were necessary for hhblits, but it turns out they're not. I removed the check for them. Can you try running it again with the latest version?

**Comment by pavlohrab** [comment]
Hey, Alex,

Yes, the problem is solved!
