### ISSUE TITLE
Missing files in exploratory mode

### ISSUE THREAD

**Issue by pavlohrab** [Alexamk/RREFinder#4]
The following error shows when running program in exploratory mode:

```
Reading in file ../rodeo2/region007.gbk
Continuing with 42 queries
Rewriting fasta
hmmsearch --cpu 1 -o output/tes5/results/RREfinder_hmm_results.txt --domtblout output/tes5/results/RREfinder_hmm_results.tbl -T 25 data/hmm/RRE_v7_phmms_3_iter.hmm output/tes5/fastas/fasta_all.fasta
Resubmitting 1 found RREs
- 12:41:59.246 ERROR: Input file (output/tes5/fastas/Contig253_7120-7474_kmtR_S1361_07170_RRE_expalign_ss.a3m) could not be opened!

Traceback (most recent call last):
  File "./RRE.py", line 1371, in <module>
    res,parsed_data_dict = main(settings)
  File "./RRE.py", line 1190, in main
    all_groups = rrefinder_main(settings,RRE_targets,all_groups)
  File "./RRE.py", line 945, in rrefinder_main
    resubmit_all(all_groups,RRE_targets,settings)
  File "./RRE.py", line 567, in resubmit_all
    resubmit_group(group,RRE_targets,settings,settings.cores)
  File "./RRE.py", line 515, in resubmit_group
    parse_hhpred_res(group,RRE_targets,settings,resubmit=True)
  File "./RRE.py", line 519, in parse_hhpred_res
    results = read_hhr(group.RRE_results_file)
  File "./RRE.py", line 365, in read_hhr
    with open(f) as inf:
FileNotFoundError: [Errno 2] No such file or directory: 'output/tes5/results/Contig253_7120-7474_kmtR_S1361_07170_RRE.hhr'
```
Can you help to solve it?

**Comment by pavlohrab** [comment]
Resolved. The problem was in Genbank File.

**Comment by pavlohrab** [comment]
The problem is still here... Precision mode works just fine.

**Comment by Alexamk** [comment]
Hello,
From your e-mail it appears the error is in the addss.pl part of HHPred. Specifically, it appears that the error occurs during parsing of the HHPaths.pm file. Can you make sure that the file contains no formatting errors?
The file should be in the same folder as the addss.pl script.

**Comment by pavlohrab** [comment]
Hi,
I am relatively new to github, so I have reopened and changed the issue (maybe opening another instead was the better option...). Missing addss.pl file issue was initially fixed simple by adding HHPaths.pm to @INC for perl. The new issue is for missing analysis files.
The problem is that file `.....RRE_expalign_ss.a3m ` really do not exist in the folder, so it cannot be oppened. Only `...RRE_expalign.a3m` file is there. (see the issue code above)
And so, there is no `..._RRE.hhr` file, only `RRE_expalign.hhr` one. 

> Hello,
> From your e-mail it appears the error is in the addss.pl part of HHPred. Specifically, it appears that the error occurs during parsing of the HHPaths.pm file. Can you make sure that the file contains no formatting errors?
> The file should be in the same folder as the addss.pl script.

**Comment by pavlohrab** [comment]
Resolved.
The easiest fix is to install hhsuite from anaconda to the same environment where you have rrefinder. No changes in HHPaths.pm required.
Addss.pl is there and all is working , although this command isn't recognizable in a terminal.

**Comment by Alexamk** [comment]
Hi,
No worries, it's pretty new for me too.
Anyway, the fact that `_RRE_expalign_ss.a3m` is missing but `_RRE_expalign.a3m` is not indicates that the problem occurs during the addss.pl step.

Please try to run RRE.py with the highest verbosity setting. It should print the system command it uses to run addss.pl, and iirc also the exact error code it displays.
Can you add the logfile? It is generated in the output folder.
