### ISSUE TITLE
Problems parsing gbk files - 'illegal characters'

### ISSUE THREAD

**Issue by Manoo-hao** [Alexamk/RREFinder#5]
I just installed RREFinder for a quick testrun and was successful with fasta files, but not with genbank files. It looks to me like something about how biopython parses seq records from gbk files has changed? I only installed up to the point where I can run the precision mode. Full disclosure - I also commented out the line '- ld_impl_linux-64=2.34=h53a641e_0' in the RREfinder.yml file as it caused issues when installing, so there is the obvious chance that I'm causing problems...

Files used:
protein fasta: 
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/017/068/035/GCF_017068035.1_ASM1706803v1/GCF_017068035.1_ASM1706803v1_protein.faa.gz
gbk: 
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/017/068/035/GCF_017068035.1_ASM1706803v1/GCF_017068035.1_ASM1706803v1_genomic.gbff.gz

Commands used:
protein fasta:
 `python RRE.py --infile path/to/GCF_017068035.1_ASM1706803v1_protein.faa --intype fasta --outputfolder path/to/outfiles/ --cores 4 --mode --verbosity 2 precision RRE_test_faa`
genbank:
 `python RRE.py --infile path/to/GCF_017068035.1_ASM1706803v1_genomic.gbff --intype genbank --outputfolder path/to/outfiles/ --cores 4 --mode precision --verbosity 2 RRE_test_gbk`

Output for genbank:
`Parse failed (sequence file ../outfiles/RRE_test_gbk/fastas/fasta_all.fasta):`
`Line 72: illegal character :`

Looking at the vicinity of line 72 of the fasta_all.fasta file showed the following:

![image](https://user-images.githubusercontent.com/10657025/121464573-36086100-ca08-11eb-81f4-f16c0529d204.png)

I tried it with a few different genbank files and end up running into the same problem sooner or later.

**Comment by Alexamk** [comment]
Hello,
RRE-Finder uses Biopython to parse the genbank files. From what I can see from the genbank file you tried, it crashes on line 72 which reads: 
                     /country="China:Jinan"
The colon is what breaks Biopython, apparently.
Have you tried updating to a more recent version of Biopython and seeing if the issue persists?

**Comment by Manoo-hao** [comment]
Hi @Alexamk 
Thanks for getting back to me.
I ran `conda update -n RREfinder --update-deps biopython` on the conda environment which updated biopython to 1.79 . Using the same input files, this did solve the issue of illegal characters I had before but gave me another biopython warning: 'BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.' 

I have only tried it with the one file, so it might be a file-specific problem. However, I get 2 hits when using a fasta input and 0 hits with the gbk input.

**Comment by Alexamk** [comment]
Turns out there was a problem with extracting the sequences from genbank files if these were not given in the "translation" tabs. I've pushed a fix for this. Let me know if this resolved the issue for you. 
Also changed the environment file so that it should not give the same problems anymore.

**Comment by Manoo-hao** [comment]
Hi again,

Thanks for the update. I re-built the environment with the recent changes and now get the same results for both, protein-fasta and gbk inputs (using the same testfiles mentioned above).
